apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-app
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: dummy-backend
                port:
                  number: 8080
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: dummy-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-frontend
                port:
                  number: 80